testing approval
module: test-vm
env: itops-playground

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -10,41 +10,43 @@ steps:
   args:
   - '-c'
   - |
-    echo $_COMMIT_MESSAGE
-  #   . <(git log -n1 | egrep '^\s+\w+\:\s\w+' | sed -Eze 's/\s+(\w+):\s(\S+)/: \${\1=\2} export \1;/g')
-    
-  #   if [ -z "$module" ] || [ -z "$env" ]; then
-  #     echo 'missing required entries: module and/or env, check the documentation'
-  #     exit 1                              
-  #   fi
 
-  #   token="$(gcloud auth print-identity-token --impersonate-service-account='cloudbuild@itops-playground.iam.gserviceaccount.com' \
-  #    --audiences='vault/cloudbuild-iam' --project="$env"  --include-email)"
-  #   vc="$(vault write -field=token auth/gcp/login     role='cloudbuild-iam'      jwt=$token)"
-  #   mv /infractl/terraform /infractl/terraform-orig
-  #   ln -s /workspace/terraform /infractl/terraform
-  #   cd /infractl
-  #   infractl --vault-token "$vc" terraform plan --module "$module" --env "$env" --upgrade-on-init --force
-
-# - id: 'terraform-apply'
-#   name: us-central1-docker.pkg.dev/itops-playground/container/infractl:latest
-#   waitFor: ['terraform-plan']
-#   entrypoint: bash
-#   env:
-#      - 'INFRACTL_HOME=/infractl' 
-#      - 'VAULT_ADDR=https://itops-playground-vault-01.corp.oreilly.com:8200'
-#   args:
-#   - '-c'
-#   - | 
-#     . <(git log -n1 | egrep '^\s+\w+\:\s\w+' | sed -Eze 's/\s+(\w+):\s(\S+)/: \${\1=\2} export \1;/g')
+    . <(git log -n1 | egrep '^\s+\w+\:\s\w+' | sed -Eze 's/\s+(\w+):\s(\S+)/: \${\1=\2} export \1;/g')
     
-#     token="$(gcloud auth print-identity-token --impersonate-service-account='cloudbuild@itops-playground.iam.gserviceaccount.com' \
-#      --audiences='vault/cloudbuild-iam' --project="$env"  --include-email)"
-#     vc="$(vault write -field=token auth/gcp/login     role='cloudbuild-iam'      jwt=$token)"
-#     mv /infractl/terraform /infractl/terraform-orig
-#     ln -s /workspace/terraform /infractl/terraform
-#     cd /infractl
-#     infractl --vault-token "$vc" terraform apply --module "$module" --env "$env" --upgrade-on-init --force
+    if [ -z "$module" ] || [ -z "$env" ]; then
+      echo 'missing required entries: module and/or env, check the documentation'
+      exit 1                              
+    fi
+
+    token="$(gcloud auth print-identity-token --impersonate-service-account='cloudbuild@itops-playground.iam.gserviceaccount.com' \
+     --audiences='vault/cloudbuild-iam' --project="$env"  --include-email)"
+    vc="$(vault write -field=token auth/gcp/login     role='cloudbuild-iam'      jwt=$token)"
+    mv /infractl/terraform /infractl/terraform-orig
+    ln -s /workspace/terraform /infractl/terraform
+    cd /infractl
+    infractl --vault-token "$vc" terraform plan --module "$module" --env "$env" --upgrade-on-init --force
+
+- id: 'terraform-apply'
+  name: us-central1-docker.pkg.dev/itops-playground/container/infractl:latest
+  waitFor: ['terraform-plan']
+  entrypoint: bash
+  env:
+     - 'INFRACTL_HOME=/infractl' 
+     - 'VAULT_ADDR=https://itops-playground-vault-01.corp.oreilly.com:8200'
+  args:
+  - '-c'
+  - | 
+    . <(git log -n1 | egrep '^\s+\w+\:\s\w+' | sed -Eze 's/\s+(\w+):\s(\S+)/: \${\1=\2} export \1;/g')
+    
+    token="$(gcloud auth print-identity-token --impersonate-service-account='cloudbuild@itops-playground.iam.gserviceaccount.com' \
+     --audiences='vault/cloudbuild-iam' --project="$env"  --include-email)"
+    vc="$(vault write -field=token auth/gcp/login     role='cloudbuild-iam'      jwt=$token)"
+    mv /infractl/terraform /infractl/terraform-orig
+    ln -s /workspace/terraform /infractl/terraform
+    cd /infractl
+    infractl --vault-token "$vc" terraform apply --module "$module" --env "$env" --upgrade-on-init --force
+  aproval:
+    description: "Look at the plan output and action accordingle"
 
 logsBucket: gs://logs_cloud_build
 options:
