testing this trigger on pull request with a filer
module: test-vm
env: itops-playground

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -30,32 +30,62 @@ steps:
   env:
      - 'INFRACTL_HOME=/infractl' 
      - 'VAULT_ADDR=https://itops-playground-vault-01.corp.oreilly.com:8200'
+  # args:
+  # - '-c'
+  # - |
+  #   if [ "$BRANCH_NAME" = "main" ]; then
+  #     . <(git log -n1 | egrep '^\s+\w+\:\s\w+' | sed -Eze 's/\s+(\w+):\s(\S+)/: \${\1=\2} export \1;/g')
+      
+  #     if [ -z "$module" ] || [ -z "$env" ]; then
+  #        echo 'missing required entries: module and/or env, check the documentation'
+  #        exit 1                              
+  #     fi
+  #     echo "***************************** TERRAFORM APPLY *******************************"
+  #     echo "************ "Runing terraform apply on '$BRANCH_NAME' branch."**************"
+  #     echo "*****************************************************************************"
+
+  #     token="$(gcloud auth print-identity-token --impersonate-service-account='cloudbuild@itops-playground.iam.gserviceaccount.com' \
+  #     --audiences='vault/cloudbuild-iam' --project="$env"  --include-email)"
+  #     vc="$(vault write -field=token auth/gcp/login     role='cloudbuild-iam'      jwt=$token)"
+  #     mv /infractl/terraform /infractl/terraform-orig
+  #     ln -s /workspace/terraform /infractl/terraform
+  #     cd /infractl
+  #     infractl --vault-token "$vc" terraform apply --module "$module" --env "$env" --upgrade-on-init --force                             
+  #   else
+  #     echo "***************************** SKIPPING APPLYING ************************************"
+  #     echo "Terraform apply runs only on branch main - skipping apply on '$BRANCH_NAME' branch."
+  #     echo "************************************************************************************"
+  #   fi
   args:
   - '-c'
   - |
-    if [ "$BRANCH_NAME" = "main" ]; then
-      . <(git log -n1 | egrep '^\s+\w+\:\s\w+' | sed -Eze 's/\s+(\w+):\s(\S+)/: \${\1=\2} export \1;/g')
-      
-      if [ -z "$module" ] || [ -z "$env" ]; then
+    . <(git log -n1 | egrep '^\s+\w+\:\s\w+' | sed -Eze 's/\s+(\w+):\s(\S+)/: \${\1=\2} export \1;/g')
+    
+    if [ -z "$module" ] || [ -z "$env" ]; then
          echo 'missing required entries: module and/or env, check the documentation'
          exit 1                              
-      fi
-      echo "***************************** TERRAFORM APPLY *******************************"
-      echo "************ "Runing terraform apply on '$BRANCH_NAME' branch."**************"
-      echo "*****************************************************************************"
-
-      token="$(gcloud auth print-identity-token --impersonate-service-account='cloudbuild@itops-playground.iam.gserviceaccount.com' \
-      --audiences='vault/cloudbuild-iam' --project="$env"  --include-email)"
-      vc="$(vault write -field=token auth/gcp/login     role='cloudbuild-iam'      jwt=$token)"
-      mv /infractl/terraform /infractl/terraform-orig
-      ln -s /workspace/terraform /infractl/terraform
-      cd /infractl
-      infractl --vault-token "$vc" terraform apply --module "$module" --env "$env" --upgrade-on-init --force                             
-    else
-      echo "***************************** SKIPPING APPLYING ************************************"
-      echo "Terraform apply runs only on branch main - skipping apply on '$BRANCH_NAME' branch."
-      echo "************************************************************************************"
     fi
+
+    echo "***************************** TERRAFORM APPLY *******************************"
+    echo "************ "Runing terraform apply on '$BRANCH_NAME' branch."**************"
+    echo "*****************************************************************************"
+
+    token="$(gcloud auth print-identity-token --impersonate-service-account='cloudbuild@itops-playground.iam.gserviceaccount.com' \
+    --audiences='vault/cloudbuild-iam' --project="$env"  --include-email)"
+    vc="$(vault write -field=token auth/gcp/login role='cloudbuild-iam' jwt=$token)"
+    mv /infractl/terraform /infractl/terraform-orig
+    ln -s /workspace/terraform /infractl/terraform
+    cd /infractl
+    infractl --vault-token "$vc" terraform apply --module "$module" --env "$env" --upgrade-on-init --force                             
+  filters:
+    branches:
+      only:
+        - 'main'
+    pullRequestFilter:
+      branches:
+        - 'main'
+      states:
+        - 'APPROVED'
 logsBucket: gs://logs_cloud_build
 options:
   pool:
